### ISSUE TITLE
Policy: MemcacheEnabled - duplicate policy

### ISSUE THREAD

**Issue by shanefjordan** [drutiny/drutiny-acquia#4]
The MemcacheEnabled policy is a duplicate of the D8 plugin MemcacheEnabled policy. We should remove this policy and update any references to the D8 plugin version. There is nothing specific about this policy for Acquia.

**Comment by fiasco** [comment]
Actually, that policy uses content copied from an Acquia source. I don't recall where, probably the AHT site-review. Its actually missing the link to our memcached documentation.

You're right that it is the exact same audit. But the differentiator is the content - its more applicable to Acquia specifically opposed to the Drupal 8 version which is more generic.

**Comment by shanefjordan** [comment]
Closed backed on feedback from Josh.
